config/routes.rb
Rails.application.routes.draw do
  resources :outgoings
  resources :incomes
  resources :categories
  resources :calendars
  resources :pockets
  resources :users

    root 'users#index'

end

app/models/pocket.rb
class Pocket < ActiveRecord::Base
  belongs_to :user
  has_many :calendars, dependent: :destroy
  has_many :incomes, dependent: :destroy
  has_many :outgoings, dependent: :destroy

  validates_presence_of :name
  validates_presence_of :user_id
end

app/controllers/pockets_controller.rb
class PocketsController < ApplicationController
  before_action :set_pocket, only: [:show, :edit, :update, :destroy]

  # GET /pockets
  # GET /pockets.json
  def index
    @pockets = Pocket.all
  end

  # GET /pockets/1
  # GET /pockets/1.json
  def show
  end

  # GET /pockets/new
  def new
    @pocket = Pocket.new
  end

  # GET /pockets/1/edit
  def edit
  end

  # POST /pockets
  # POST /pockets.json
  def create
    @pocket = Pocket.new(pocket_params)

    respond_to do |format|
      if @pocket.save
        format.html { redirect_to @pocket, notice: 'Pocket was successfully created.' }
        format.json { render :show, status: :created, location: @pocket }
      else
        format.html { render :new }
        format.json { render json: @pocket.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /pockets/1
  # PATCH/PUT /pockets/1.json
  def update
    respond_to do |format|
      if @pocket.update(pocket_params)
        format.html { redirect_to @pocket, notice: 'Pocket was successfully updated.' }
        format.json { render :show, status: :ok, location: @pocket }
      else
        format.html { render :edit }
        format.json { render json: @pocket.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /pockets/1
  # DELETE /pockets/1.json
  def destroy
    @pocket.destroy
    respond_to do |format|
      format.html { redirect_to pockets_url, notice: 'Pocket was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_pocket
      @pocket = Pocket.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def pocket_params
      params.require(:pocket).permit(:name, :user_id)
    end
end

app/helpers/pockets_helper.rb
module PocketsHelper
end

app/views/pockets/_form.html.erb
<%= form_for(@pocket) do |f| %>
  <% if @pocket.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@pocket.errors.count, "error") %> prohibited this pocket from being saved:</h2>

      <ul>
      <% @pocket.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :user_id %><br>
    <%= f.select(:user_id) do %>
    <%= options_from_collection_for_select(User.all, :id, :name) %>
    <% end %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/pockets/edit.html.erb
<h1>Editing Pocket</h1>

<%= render 'form' %>

<%= link_to 'Show', @pocket %> |
<%= link_to 'Back', pockets_path %>

app/views/pockets/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Pockets</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>User</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @pockets.each do |pocket| %>
      <tr>
        <td><%= pocket.name %></td>
        <td><%= pocket.user.name %></td>
        <td><%= link_to 'Show', pocket %></td>
        <td><%= link_to 'Edit', edit_pocket_path(pocket) %></td>
        <td><%= link_to 'Destroy', pocket, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Pocket', new_pocket_path %>

app/views/pockets/new.html.erb
<h1>New Pocket</h1>

<%= render 'form' %>

<%= link_to 'Back', pockets_path %>

app/views/pockets/show.html.erb
<p id="notice"><%= notice %></p>

<h1>Show Pocket</h1>
<p>
  <strong>ID:</strong>
  <%= @pocket.id %>
</p>
<p>
  <strong>Name:</strong>
  <%= @pocket.name %>
</p>
<p>
  <strong>User:</strong>
  <%= link_to @pocket.user.name, user_path(@pocket.user.id) %>
</p>
<p>
<strong>Incomes:</strong>
  <ul>
    <% @pocket.incomes.each do |income| %>
        <li><%= link_to income.note, income_path(income.id) %></li>
    <% end %>
  </ul>
</p>
<p>
<strong>Outgoings:</strong>
  <ul>
    <% @pocket.outgoings.each do |outgoing| %>
        <li><%= link_to outgoing.note, outgoing_path(outgoing.id) %></li>
    <% end %>
  </ul>
</p>
<p>
<strong>Calendars:</strong>
  <ul>
    <% @pocket.calendars.each do |calendar| %>
        <li><%= link_to calendar.period, calendar_path(calendar.id) %></li>
    <% end %>
  </ul>
</p>

<%= link_to 'Edit', edit_pocket_path(@pocket) %> |
<%= link_to 'Back', pockets_path %>