config/routes.rb
Rails.application.routes.draw do
  resources :outgoings
  resources :incomes
  resources :categories
  resources :calendars
  resources :pockets
  resources :users

    root 'users#index'

end

app/models/outgoing.rb
class Outgoing < ActiveRecord::Base
  belongs_to :category
  belongs_to :pocket
  belongs_to :user

  validates_presence_of :date
  validates_presence_of :sum
  validates_presence_of :category_id
  validates_presence_of :pocket_id
  validates_presence_of :user_id
end

app/controllers/outgoings_controller.rb
class OutgoingsController < ApplicationController
  before_action :set_outgoing, only: [:show, :edit, :update, :destroy]

  # GET /outgoings
  # GET /outgoings.json
  def index
    @outgoings = Outgoing.all
  end

  # GET /outgoings/1
  # GET /outgoings/1.json
  def show
  end

  # GET /outgoings/new
  def new
    @outgoing = Outgoing.new
  end

  # GET /outgoings/1/edit
  def edit
  end

  # POST /outgoings
  # POST /outgoings.json
  def create
    @outgoing = Outgoing.new(outgoing_params)

    respond_to do |format|
      if @outgoing.save
        format.html { redirect_to @outgoing, notice: 'Outgoing was successfully created.' }
        format.json { render :show, status: :created, location: @outgoing }
      else
        format.html { render :new }
        format.json { render json: @outgoing.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /outgoings/1
  # PATCH/PUT /outgoings/1.json
  def update
    respond_to do |format|
      if @outgoing.update(outgoing_params)
        format.html { redirect_to @outgoing, notice: 'Outgoing was successfully updated.' }
        format.json { render :show, status: :ok, location: @outgoing }
      else
        format.html { render :edit }
        format.json { render json: @outgoing.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /outgoings/1
  # DELETE /outgoings/1.json
  def destroy
    @outgoing.destroy
    respond_to do |format|
      format.html { redirect_to outgoings_url, notice: 'Outgoing was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_outgoing
      @outgoing = Outgoing.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def outgoing_params
      params.require(:outgoing).permit(:note, :date, :sum, :category_id, :pocket_id, :user_id)
    end
end

app/helpers/outgoings_helper.rb
module OutgoingsHelper
end

app/views/outgoings/_form.html.erb
<%= form_for(@outgoing) do |f| %>
  <% if @outgoing.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@outgoing.errors.count, "error") %> prohibited this outgoing from being saved:</h2>

      <ul>
      <% @outgoing.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :note %><br>
    <%= f.text_field :note %>
  </div>
  <div class="field">
    <%= f.label :date %><br>
    <%= f.date_select :date %>
  </div>
  <div class="field">
    <%= f.label :sum %><br>
    <%= f.text_field :sum %>
  </div>
  <div class="field">
    <%= f.label :user_id %><br>
    <%= f.select(:user_id) do %>
    <%= options_from_collection_for_select(User.all, :id, :name) %>
    <% end %>
  </div>
  <div class="field">
    <%= f.label :pocket_id %><br>
    <%= f.select(:pocket_id) do %>
    <%= options_from_collection_for_select(Pocket.all, :id, :name) %>
    <% end %>
  </div>
  <div class="field">
    <%= f.label :category_id %><br>
    <%= f.select(:category_id) do %>
    <%= options_from_collection_for_select(Category.all, :id, :name) %>
    <% end %>
  </div>
  <br>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/outgoings/edit.html.erb
<h1>Editing Outgoing</h1>

<%= render 'form' %>

<%= link_to 'Show', @outgoing %> |
<%= link_to 'Back', outgoings_path %>

app/views/outgoings/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Outgoings</h1>

<table>
  <thead>
    <tr>
      <th>Note</th>
      <th>Date</th>
      <th>Sum</th>
      <th>Category</th>
      <th>Pocket</th>
      <th>User</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @outgoings.each do |outgoing| %>
      <tr>
        <td><%= outgoing.note %></td>
        <td><%= outgoing.date %></td>
        <td><%= outgoing.sum %></td>
        <td><%= outgoing.category.name %></td>
        <td><%= outgoing.pocket.name %></td>
        <td><%= outgoing.user.name %></td>
        <td><%= link_to 'Show', outgoing %></td>
        <td><%= link_to 'Edit', edit_outgoing_path(outgoing) %></td>
        <td><%= link_to 'Destroy', outgoing, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Outgoing', new_outgoing_path %>

app/views/outgoings/new.html.erb
<h1>New Outgoing</h1>

<%= render 'form' %>

<%= link_to 'Back', outgoings_path %>

app/views/outgoings/show.html.erb
<p id="notice"><%= notice %></p>

<h1>Show Outgoing</h1>
<p>
  <strong>ID:</strong>
  <%= @outgoing.id %>
</p>
<p>
  <strong>Note:</strong>
  <%= @outgoing.note %>
</p>

<p>
  <strong>Date:</strong>
  <%= @outgoing.date %>
</p>

<p>
  <strong>Sum:</strong>
  <%= @outgoing.sum %>
</p>

<p>
  <strong>Category:</strong>
  <%= link_to @outgoing.category.name, category_path(@outgoing.category.id) %>
</p>

<p>
  <strong>Pocket:</strong>
  <%= link_to @outgoing.pocket.name, pocket_path(@outgoing.pocket.id) %>
</p>

<p>
  <strong>User:</strong>
  <%= link_to @outgoing.user.name, user_path(@outgoing.user.id) %>
</p>

<%= link_to 'Edit', edit_outgoing_path(@outgoing) %> |
<%= link_to 'Back', outgoings_path %>