config/routes.rb
Rails.application.routes.draw do
  resources :outgoings
  resources :incomes
  resources :categories
  resources :calendars
  resources :pockets
  resources :users

    root 'users#index'

end

app/models/category.rb
class Category < ActiveRecord::Base
  belongs_to :user
  has_many :incomes, dependent: :destroy
  has_many :outgoings, dependent: :destroy

  validates_presence_of :name
  validates_presence_of :user_id
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :set_category, only: [:show, :edit, :update, :destroy]

  # GET /categories
  # GET /categories.json
  def index
    @categories = Category.all
  end

  # GET /categories/1
  # GET /categories/1.json
  def show
  end

  # GET /categories/new
  def new
    @category = Category.new
  end

  # GET /categories/1/edit
  def edit
  end

  # POST /categories
  # POST /categories.json
  def create
    @category = Category.new(category_params)

    respond_to do |format|
      if @category.save
        format.html { redirect_to @category, notice: 'Category was successfully created.' }
        format.json { render :show, status: :created, location: @category }
      else
        format.html { render :new }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /categories/1
  # PATCH/PUT /categories/1.json
  def update
    respond_to do |format|
      if @category.update(category_params)
        format.html { redirect_to @category, notice: 'Category was successfully updated.' }
        format.json { render :show, status: :ok, location: @category }
      else
        format.html { render :edit }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /categories/1
  # DELETE /categories/1.json
  def destroy
    @category.destroy
    respond_to do |format|
      format.html { redirect_to categories_url, notice: 'Category was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_category
      @category = Category.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def category_params
      params.require(:category).permit(:name, :way, :user_id)
    end
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/views/categories/_form.html.erb
<%= form_for(@category) do |f| %>
  <% if @category.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@category.errors.count, "error") %> prohibited this category from being saved:</h2>

      <ul>
      <% @category.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :way %> (tick if outgoing-category)<br>
    <%= f.check_box :way %>
  </div>
  <div class="field">
    <%= f.label :user_id %><br>
    <%= f.select(:user_id) do %>
    <%= options_from_collection_for_select(User.all, :id, :name) %>
    <% end %>
  </div>
  <br>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/categories/edit.html.erb
<h1>Editing Category</h1>

<%= render 'form' %>

<%= link_to 'Show', @category %> |
<%= link_to 'Back', categories_path %>

app/views/categories/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Categories</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Way</th>
      <th>User</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @categories.each do |category| %>
      <tr>
        <td><%= category.name %></td>
        <td><%= category.way %></td>
        <td><%= category.user.name %></td>
        <td><%= link_to 'Show', category %></td>
        <td><%= link_to 'Edit', edit_category_path(category) %></td>
        <td><%= link_to 'Destroy', category, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Category', new_category_path %>

app/views/categories/new.html.erb
<h1>New Category</h1>

<%= render 'form' %>

<%= link_to 'Back', categories_path %>

app/views/categories/show.html.erb
<p id="notice"><%= notice %></p>

<h1>Show Category</h1>

<p>
  <strong>ID:</strong>
  <%= @category.id %>
</p>
<p>
  <strong>Name:</strong>
  <%= @category.name %>
</p>
<p>
  <strong>Way:</strong>
  <%= @category.way %>
</p>
<p>
  <strong>User:</strong>
  <%= link_to @category.user.name, user_path(@category.user.id) %>
</p>
<% if(@category.way == false) %>
	<p>
	<strong>Incomes:</strong>
	  <ul>
	    <% @category.incomes.each do |income| %>
	        <li><%= link_to income.note, income_path(income.id) %></li>
	    <% end %>
	  </ul>
	</p>
<% end %> 
<% if(@category.way == true) %>
	<p>
	<strong>Outgoings:</strong>
	  <ul>
	    <% @category.outgoings.each do |outgoing| %>
	        <li><%= link_to outgoing.note, outgoing_path(outgoing.id) %></li>
	    <% end %>
	  </ul>
	</p>
<% end %> 

<%= link_to 'Edit', edit_category_path(@category) %> |
<%= link_to 'Back', categories_path %>